name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  web-and-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Type check root
        run: npm run lint

      - name: Build root
        run: npm run build

      - name: Install API dependencies
        run: npm ci
        working-directory: api

      - name: Build API
        run: npm run build
        working-directory: api
